jobs:
  pr-title:
    name: Lint PR title
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: amannn/action-semantic-pull-request@v3
      with:
        validateSingleCommit: true
name: Lint PR Title
on:
  repository_dispatch:
    types: trigger-ga___lint-pr-title.yml
