jobs:
  pr-run-test-action:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.head_ref }}
    name: Check if "Run tests" action succeeded
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: node install
      run: cd ./.github/helpers && npm i
    - continue-on-error: true
      name: Calling github API
      run: cd ./.github/helpers && GITHUB_TOKEN=${{ github.token }} REPO=${{ github.repository
        }} RUN_ID=${{ github.run_id }} BRANCH=${{ github.head_ref }} JOB_ID=${{ github.job
        }} SOURCE_OWNER=${{ github.event.pull_request.head.repo.owner.login }} CURRENT_SHA=${{
        github.event.pull_request.head.sha }} node node_modules/github-workflow-helpers/test-pass-check-pr.js
    timeout-minutes: 60
name: Check if "Run tests" action succeeded
on:
  repository_dispatch:
    types: trigger-ga___tests-pass-check-pr.yml
