jobs:
  test_job:
    container: rishabhpoddar/supertokens_core_testing
    name: Run tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Cloning supertokens-root
      run: cd ../ && git clone https://github.com/supertokens/supertokens-root.git
    - continue-on-error: true
      name: Update Java 1
      run: update-alternatives --install "/usr/bin/java" "java" "/usr/java/jdk-15.0.1/bin/java"
        2
    - continue-on-error: true
      name: Update Java 2
      run: update-alternatives --install "/usr/bin/javac" "javac" "/usr/java/jdk-15.0.1/bin/javac"
        2
    - continue-on-error: true
      name: Modifying modules.txt in supertokens-root
      run: cd ../supertokens-root && echo "core,master\nplugin-interface,${{ github.event.inputs.pluginInterfaceBranch
        }},${{ github.event.inputs.pluginRepoOwnerName }}" > modules.txt
    - continue-on-error: true
      name: Contents of modules.txt
      run: cat ../supertokens-root/modules.txt
    - continue-on-error: true
      name: Running loadModules in supertokens-root
      run: cd ../supertokens-root && ./loadModules
    - continue-on-error: true
      name: Copying current supertokens-core branch into supertokens-root
      run: cd ../supertokens-root && rm -rf ./supertokens-core && cp -r ../supertokens-core
        ./
    - continue-on-error: true
      name: Building and running tests
      run: cd ../supertokens-root && ./startTestingEnv
    timeout-minutes: 60
name: Run tests
on:
  repository_dispatch:
    types: trigger-ga___tests.yml
